### ISSUE TITLE
Found several error

### ISSUE THREAD

**Issue by 0xprune** [nixentric/Lowkey-Hugo-Theme#16]
Im in hugo new version (v0.12.4), found several error:
1. When im running hugo server after follow install guide, then
`Error: command error: failed to load modules: module "enhanced-lowkey" not found in "/home/ekydiza/ekydiza.com/themes/enhanced-lowkey"; either add it as a Hugo Module or store it in "/home/ekydiza/ekydiza.com/themes".: module does not exist `

2. After change name folder to _enhanced-lowkey_, and rebuild, i found this error on
Built in 659 ms
```
Error: error building site: POSTCSS: failed to transform "css/tailwind.css" (text/css): /home/ekydiza/ekydiza.com/node_modules/postcss-load-config/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ekydiza/ekydiza.com/node_modules/postcss-load-config/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I love this theme, thank u if u can help my issue 💜

**Comment by 0xprune** [comment]
okay fix it, here my steps:
1. change theme name on theme.toml from _enhanced-lowkey_ to _lowkey_
2. update nodejs to new version (v14) and rebuild

case closed 💜

**Comment by 0xprune** [comment]
okay fix it, here my steps:

1. change theme name on theme.toml from enhanced-lowkey to lowkey
2. update nodejs to new version (v14) and rebuild

case closed 💜
